### ISSUE TITLE
l vs 1

### ISSUE THREAD

**Issue by ale37911** [csdms/espin#18]
Can I suggest using a different font that more clearly/easily/readably differentiates between l and 1 in code font? I am related to a lot of dsylexics and it's hard for me to tell the difference half the time. I'm not even sure if you can change this in github, but if you can, it might be helpful...

**Comment by mdpiper** [comment]
@ale37911 Yeah, this is the font used by the GitHub website.

**Comment by mdpiper** [comment]
As a workaround, a person can change the fixed-width font preference in their browser.
